apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliveggie-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliveggie-microservice
  template:
    metadata:
      labels:
        app: deliveggie-microservice
    spec:
      containers:
      - name: deliveggie-microservice
        image: harikrishnan1996/deliveggie-microservice:v2.0
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliveggie-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliveggie-gateway
  template:
    metadata:
      labels:
        app: deliveggie-gateway
    spec:
      containers:
      - name: deliveggie-gateway
        image: harikrishnan1996/deliveggie-gateway:v1.0
        ports:
        - containerPort: 80
        - containerPort: 443
        ports:
        - name: http
          containerPort: 80
          hostPort: 44350
        - name: https
          containerPort: 443
          hostPort: 44360
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliveggie-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliveggie-ui
  template:
    metadata:
      labels:
        app: deliveggie-ui
    spec:
      containers:
      - name: deliveggie-ui
        image: harikrishnan1996/deliveggie-ui:v1.0
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: deliveggie-microservice
spec:
  type: ClusterIP
  selector:
    app: deliveggie-microservice
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: deliveggie-gateway
spec:
  type: NodePort
  selector:
    app: deliveggie-gateway
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: deliveggie-ui
spec:
  type: NodePort
  selector:
    app: deliveggie-ui
  ports:
  - name: http
    port: 8001
    targetPort: 8001
