apiVersion: v1
kind: Service
metadata:
  name: deliveggiedb
  labels:
    app: deliveggiedb
spec:
  selector:
    app: deliveggiedb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliveggiedb
spec:
  selector:
    matchLabels:
      app: deliveggiedb
  replicas: 1
  template:
    metadata:
      labels:
        app: deliveggiedb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
